### ISSUE TITLE
Редактирование текста новости

### ISSUE THREAD

**Issue by umputun** [radio-t/rtnews-ui#10]
Иногда у нас просиходит странное , типа вот этого http://rtnews.vyrtsev.com/post/the-consistency-of-arithmetic-pdf. Тут, несомненно, прoблема в том, что pdf однако бывают и другие случаи когда хочется поправить тeкст руками.

На стороне UI для этого можно использовать существующий `POST /api/v1/news/manual` поменяв в body только `content` и `snippet`

**Comment by umputun** [comment]
cc @Reeywhaar

**Comment by reeywhaar** [comment]
oki doki

**Comment by reeywhaar** [comment]
Добрался до части где надо сохранять. А почему `POST`? Это же создание, как бэкенд старый удалит?

Я вижу это как
```
PUT /api/v1/news/:id
или
PUT /api/v1/news/edit/:id

{
    "content": "new content"
}
```

И еще вопрос, должно ли редактирование snippet и content быть раздельным, или snippet сам генерируется из content?

p.s прототип на http://rtnews.vyrtsev.com/post/cycle-js

**Comment by umputun** [comment]
это метод уже есть в API и он позволяет добавить новость и/или поменять. Все, что он делает это upsert по совпадению `title`. Т.е. если title совпадет то будет обновление, если нет - добавление.

Для редактирования UI должен поменять все, что надо (в нашем случае content и snippet) и вызвать этот POST. Т.к. это метод для ручного добавления, то автоматически он делает только самую малость:

- обнoвляет `ts`и `ats`
- устанавлиевает `slug` из `title`
- копирует `link` to `origlink`

**Comment by umputun** [comment]
реализовано в #12
