### ISSUE TITLE
UI забывает что я админ

### ISSUE THREAD

**Issue by umputun** [radio-t/rtnews-ui#13]
@Reeywhaar - все еще происходит и нередко. UI теряет знание что я админ после разных переходов. Не знаю как это надежно повторить, но на практике случается

**Comment by reeywhaar** [comment]
Да, знаю, что-то такое есть, пытаюсь разобраться, но никак не могу воспроизвести точно, у меня очень редко случается.
После перехода на /login логинит без пароля и как будто всё хорошо.

**Comment by umputun** [comment]
Влил #14, обновил

**Comment by reeywhaar** [comment]
Вижу, что на news.radio-t.com версия не обновилась, возможно это связано с #15

**Comment by umputun** [comment]
все еще забывает

**Comment by reeywhaar** [comment]
Хм, я вижу что на news.radio-t.com версия на момент тега 1.1.0, там нет фикса. Что может быть не так? Докерфайл работает, все без ошибок. Не понимаю.

**Comment by umputun** [comment]
вроде заенфорсил

**Comment by reeywhaar** [comment]
Вот, сейчас вижу обновилось. Теперь фикс есть, но работает ли.

**Comment by umputun** [comment]
и все еще забывает. Обычно это просизодит после перехода с главной страницы на страницу новости. Я в принципе не понимаю, что UI вообще делает с auth. На мой взгляд ему только надо редиректить Unauthorized на страницу логина и потом делать то, что надо чтоб послать basic auth. С этого момента браузер все запомнит и никаких локальных запоминаний и/или кук не надо для этого.

Если basic auth это такая суровая проблема для UI я, наверное, могу все это поменять и делать на своей стороне сессией, хотя как-то странно - раньше такого не происходило

**Comment by reeywhaar** [comment]
Хммм, а в консоли есть что-нибудь? Это в хроме, сафари, или везде?
UI делает так: после логина сохраняет cookie: auth=base64("user:login") и потом переиспользует эту куки для всех реквестов в Authorization хедере. При заходе проверяет авторизацию посылая get на `/api/v1/news/reload` и ставит результат в стэйт приложения. Почему-то при переходе на новость, этот стэйт ресетится или что там с ним.

Нет, basic auth совсем не проблема, тут где-то у меня ошибка, но я уже очень долго не могу её вопроизвести.

**Comment by umputun** [comment]
это сафари, в других не пробовал. Но вроде я нашел как это воспроизвести конситентно: после перехода на ссылку новости (на ориг. сайт) и потом back - вот это отлогинивает

**Comment by umputun** [comment]
ошибок в консоли нет, оно там что-то про gitter пишет, но видимо это неважно.

**Comment by reeywhaar** [comment]
No luck, попробовал, но все равно не могу. А кука auth присутствует после возвращения?

**Comment by umputun** [comment]
кука пишится после логина но исчезает после возврата. может ты ее делаешь сессионной?

**Comment by umputun** [comment]
вообще эта твоя кука дело довольно стремное. Насколько я понимаю, мы подвержены CSRF. Раньше оно вроде в localstore хранило, зачем нам вообще кука? и от туда точно ничего не исчезает само по себе.

**Comment by reeywhaar** [comment]
Понаписал, удалил. Да, перенесу в localStorage пока.

**Comment by umputun** [comment]
все на вид стабильно, не теряет
