### ISSUE TITLE
Стало плохо

### ISSUE THREAD

**Issue by umputun** [radio-t/rtnews-ui#19]
1. не работает поехали
1. выбранная новость доходит не всем

**Comment by reeywhaar** [comment]
Я добавил пр #18, это наверное связано. Протестировал на https://rtnews.vyrtsev.com (направил его на https://news.radio-t.com/api/v1). У меня работает, "поехали", тема выбирается.

**Comment by reeywhaar** [comment]
Что-то странное происходит, stream.radio-t.com говорит "не в силах". Отваливается иногда.

**Comment by umputun** [comment]
не, это было результатом моих судорожных попыток на ходу все перезапустить. не помоголо

**Comment by umputun** [comment]
> Я добавил пр #18, это наверное связано.

Связано? Т.е. оно post не могло сделеать а auth потому что теряло куку? Я не выходил вообще по внешним ссылкам и оно думало что я залогинен. В ином случае я бы не видел "поехали" вообще. Оно конкретно сломалось, я даже api проверил, все на вид правильно

**Comment by reeywhaar** [comment]
Честно говоря, не знаю в чем на самом деле проблема. У меня все работает. Видимо есть какие-то различия между тестовым и продакшн апи. Можешь на https://rtnews.vyrtsev.com протестировать, все ли сейчас нормально? Там версия с localStorage. Осторожно, там не тестовый апи.

**Comment by umputun** [comment]
[Error] Blocked https://news.radio-t.com/api/v1/show/start?timestamp=1544311914803 from asking for credentials because it is a cross-origin request.

это в сафари. upd: в хроме тоже самое. Этого запроса я вообще не вижу на стороне сервера, что понятно - его не пропускает вообще. Но какого оно вдруг стало  cross-origin ?

**Comment by umputun** [comment]
<img width="1428" alt="mxhzx-201812-08173845-koih1" src="https://user-images.githubusercontent.com/535880/49691807-2692bf00-fb10-11e8-9815-531a2a134ef1.png">

**Comment by reeywhaar** [comment]
Так, я понял что различие в том, что тестовый на http, а прод на https.
У сафари есть пунктик[[1]](https://github.com/cyu/rack-cors/issues/116)[[2]](https://forums.developer.apple.com/thread/96501) чтобы при preflight request нужно чтобы в ответе был `Origin` в `Access-Control-Allow-Headers` от сервера.
Но это не точно. Можешь для точности завести https на jess.umputun.com, пожалуйста?

**Comment by umputun** [comment]
там похоже этот cross-origin результат упавшего POST. Я обновил версии с #18, починилось

**Comment by reeywhaar** [comment]
Странная ситуация все же. Я так понял залогиниться получилось, но кнопка "поехали" не работала. Чем реквест на допустим `/news/reload` отличается от `/show/start` для сафари? Загадка.

**Comment by umputun** [comment]
/show/start это запрос с авторизацией, на него и приходил отлуп

**Comment by reeywhaar** [comment]
Сделал proxy_pass https://rtnews.vyrtsev.com/api/v1 -> http://jess.umputun.com:8780/api/v1
Буду смотреть.

**Comment by grayodesa** [comment]
Мне кажется, что проблема скорее локальная — я "Поехали" не нажимал, но все выборы текущих тем у меня срабатывали.

**Comment by umputun** [comment]
то, что у тебя работало подозреваю связанно с тем, что твоя UI news не была обновлена и старая версия работала. Я пробовал их 2х браузеров, закрывал/открывал, ничего не помогало пока не поменяли auth хранилище.

@Reeywhaar – я вспомнил, что я еще необычного сделал. Перед началом я почистил все куки и все из localstorage

**Comment by grayodesa** [comment]
Кажется, я зашел на news вчера утром или позавчера даже, так что да, возможно, у меня была старая версия.

**Comment by reeywhaar** [comment]
@umputun я не пойму, сейчас то все нормально или что-то еще не так? Мне все же интересно, почему кука удалялась, я не удалял, expire стоял на три года.

**Comment by umputun** [comment]
сейчас все нормально, да
