### ISSUE TITLE
возможность делать временную метку для тем слушателей

### ISSUE THREAD

**Issue by umputun** [radio-t/rtnews-ui#20]
Gray выдвинул хорошую идею:

> а соорудите как-то возможность делать метку для тем слушателей. Наверное, это надо где-то рядом с «Поехали» воткнуть.

Не уверен про место, подозреваю что где-то сверху надо. Для того, чтоб оно сработало надо 3 вещи вызвать:
- взять по site api тему
- добавить по news api
- активировать

**Comment by grayodesa** [comment]
Ссылка просится где-то рядом с "Поехали" в верхнем меню. Или оторвать их обе в отдельный блок.
Учитывая, что внутри мы все равно разные темы не разделяем, достаточно поставить одну метку "Темы слушателей."

**Comment by reeywhaar** [comment]
Сделал прототип на https://rtnews.vyrtsev.com/
Пока не пушу, надо еще посмореть.

Кстати было бы хорошо если бы `POST /api/v1/news[/manual]` не возвращал `200 No Content` сразу, а возвращал ответ после добавления в бд и отвечал либо добавленным [`article record`](https://github.com/radio-t/rtnews-ui#article-news-records) либо `article.id`. Я сейчас при добавлении новости, просто жду через timeout и retry, наобум.

**Comment by umputun** [comment]
три строки выглядят очень странно. Можно убрать вобще ссылку на обновление базы (я ее никогда не нажима), сократить "Сортировать темы" на "Сортировать", сократить "Управление фидами"  над "Фиды" и "Начать темы слушателей" на "Темы слушателей". Видимо тогда все в строку влезет.

**Comment by umputun** [comment]
> было бы хорошо если бы POST /api/v1/news[/manual] не возвращал 200 No Content сразу, а возвращал ответ после добавления 

это невозможно с этим вызовом, он асинхронный и такого не знает и сам. В приниципе можно это сделать вернув "request_id" и новый блокирующий  /api/v1/news/req/{id} который вернет article по готовности. Можно и новый блокирующи POST. Но это слишком много телеодвижений для такой минорной штуки. Ждать секунду на твоей стороне (с повтором) вплоне пойдет пока.

**Comment by reeywhaar** [comment]
Поправил хедер, да стало лучше.

Про вызов понятно, no pressure.

**Comment by umputun** [comment]
добавил `POST /api/v1/news/blocking` который возвращает весь article json после добавления. Подозреваю, что будет работать, хотя детально не тестировал. Поставил на jess

**Comment by umputun** [comment]
видимо тут надо тоже поменять текст на "Таки темы слушателей?" 
<img width="537" alt="9fnvx_20181209_203413 0b8bq" src="https://user-images.githubusercontent.com/535880/49707665-ead02600-fbf1-11e8-8039-4e709566fea1.png">
