### ISSUE TITLE
Автоматизация "Поехали"

### ISSUE THREAD

**Issue by umputun** [radio-t/rtnews-ui#22]
Непонятно, как этому можно помочь, но на практике я иногда забываю нажать "Поехали". Хорошо бы придумать какую автоматизацию которая помогла бы вспомнить. Например, если не нажата до  14:15 показать ненавязчивый, но явно видимый диалог, который напомнит. `GET /api/v1/show/start` поможет понять была нажата или нет.

Скорее всего подобное нажатие по напоминанию будет неточным (поздним). Хорошо бы опционально спросить "сколько минут прошло от начала?" и использовать ответ посредством `POST /api/v1/show/start/{dtime}`

**Comment by reeywhaar** [comment]
А в каком формате `dtime` и вообще, какого вида реквест? В readme ничего нет на эту тему. Или это в планах?
POST /api/v1/show/start/5 Bad Request
POST /api/v1/show/start/2018-12-16T17%3A49%3A16.974000000-06%3A00 Bad Request

**Comment by umputun** [comment]
формат времени `20060102-150405` (yyyymmdd-hhmmss), т.е. "20181216-164500"

запрос будет `PUT /api/v1/show/start/20181216-164500` (про POST это была описка, это PUT). Время в локальной TZ

**Comment by reeywhaar** [comment]
Заметил, что `PUT /api/v1/show/start/20181216-164500` возможно не дергает хуки (гиттер и т.д.), судя по тому, что он очень быстро выполняется.

**Comment by umputun** [comment]
он не дергает умышленно, т.к посылать в гиттер сигнал начала уже бесмыленно.
