### ISSUE TITLE
Избавиться от disqus

### ISSUE THREAD

**Issue by umputun** [radio-t/rtnews-ui#3]
это, похоже, последнее место, где у нас остался disqus. Было бы логично переключить на ремарк42. Если это не сильно сложно то стоит сделать. Однако, если с этим какие-то заморочки, то можно и просто отключить комменты.

**Comment by reeywhaar** [comment]
А можно ли поднять тестовый сервер, или докер контейнер? Я так понимаю при разработке он висел на "http://master.radio-t.com:8780/api/v1". Я бы хотел переписать приложение на реакте (прототип есть на https://github.com/Reeywhaar/rtnews-ui/tree/react-batteries), но сейчас не могу протестировать админский функционал.

**Comment by umputun** [comment]
поднял на `http://jess.umputun.com:8780`

```
http http://jess.umputun.com:8780/api/v1/ping
HTTP/1.1 200 OK
App-Name: rt-news
App-Version: 70ff942-3752-develop-20171129-22:07:57
Application-Name: rt-news
Connection: keep-alive
Content-Length: 4
Content-Type: text/plain; charset=UTF-8
Date: Sat, 03 Nov 2018 17:54:38 GMT
Org: Umputun
Org: Radio-T
Server: nginx/1.14.0

pong
```

**Comment by reeywhaar** [comment]
Спасибо! Только там отсутствуют cors хедеры
```
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS
Access-Control-Allow-Headers: Content-Type, Authorization, X-Requested-With
```

**Comment by umputun** [comment]
починил

**Comment by reeywhaar** [comment]
Спасибо! И еще вопрос, есть ли какой-то логин/пароль туда? Я не нашел ничего в readme. Моя почта: reeywhaar@gmail.com

**Comment by umputun** [comment]
послал
