### ISSUE TITLE
постоянные запросы на обновление счетчика коментов

### ISSUE THREAD

**Issue by umputun** [radio-t/rtnews-ui#31]
`POST - /api/v1/counts?site=rtnews - 6e8c499551fb - 200 (35535) - 748.258µs  ["https://news.radio-t.com/post/5-things-you-can-do-to-write-better-code","https://news.radio-t.com/post/do-a-majority-of-google-developers-use-visual-studio-code-microsoft-declines-to-back-up-its-top-marketing-exec-s-claim","https://news.radio-t.com/post/gaia-build-powerful-pipelines-in-any-programming-language","https://news.radio-t.com/post/bootstrap-builder-for-busy-developers","https://news.radio-t.com/post/bootstrap-studio-the-revolutionary-web-design-tool","https://news.radio-t.com/post/movim-blog-happy-birthday-xmpp-20th-anniversary-of-1st-jabber-server","https://news.radio-t.com/post/open-source-business-models-considered-harmful-john-mark-medium","https://news.radio-t.com/post/monorepo-please-do-adam-jacob-medium","https://news.radio-t.com/post/monorepos-please-don-t-matt-klein-medium","https://news.radio-t.com/post/how-developers-will-work-in-2019","https://news.radio-t.com/post/looking-forward-to-2019-let-s-encrypt-free-ssl-tls-certificates","https://news.radio-t.com/post/microsoft-totally-changed...`

Вот такое посылается постоянно и это не есть хорошо.

**Comment by reeywhaar** [comment]
Это запрос на remark42.radio-t.com? Я counts беру из https://news.radio-t.com/api/v1/news а он, видимо, уже дергает ремарк?

**Comment by umputun** [comment]
это на моей стороне, обновляет счетчики каждую минуту. Посмотрю на досуге почему и зачем
