### ISSUE TITLE
Opening the original links in other tabs

### ISSUE THREAD

**Issue by umputun** [radio-t/rtnews-ui#34]
Currently, click on the original link processed within the current browser tab/window. This is super annoying and I'd prefer those with `target="_blank"`

<img width="1445" alt="f8bbi-201904-06135435-p8h9b" src="https://user-images.githubusercontent.com/535880/55673933-0bdd1680-5874-11e9-9db1-d7c6dc58f3a8.png">

**Comment by reeywhaar** [comment]
Well, I'm personally think that `_blank` is a gift of satan to marketologists. Why not middle click or something? But anyway.

**Comment by umputun** [comment]
thx. in this context this is all about the convenience of the host. I'm constantly clicking on it and navigating away from the news page
