### ISSUE TITLE
Переключить UI на news.radio-t.com

### ISSUE THREAD

**Issue by umputun** [radio-t/rtnews-ui#6]
Для этого нужен autobuild на dockerhub и поменать композ на мастере

**Comment by umputun** [comment]
добавил https://hub.docker.com/r/umputun/rtnews-ui/ и поменял композе и это поломало все :(

Я не очень помнимаю, как оно теперь должно доставлять UI и зачем это вообще поменяли. Там зачем-то экспозится 9000 порт, это для чего? Если, как я и ожидаю, оно строит все в /app/public то для этого не было VOLUME (добавил)

cc @Reeywhaar @igoradamenko

**Comment by reeywhaar** [comment]
9000 экспозится для дев сервера.
Я не знаю какой у тебя пайплайн, но я делаю `make dockerBuild && make dockerBuildPublic`, после чего в папке public все нужные файлы. Дальше дело за тобой, как-то доставить на сервер и прописать роут на rss, а fallback на index.html.
В docker-compose.yml директории уже сматчены.

**Comment by reeywhaar** [comment]
Что-то такое надо добавить в твой основной пайплайн
```
FROM node:10-alpine AS rtnews_frontend
COPY ./ /app/
RUN \
	cd /app && \
	npm ci --loglevel error && \
	./node_modules/.bin/webpack --mode production

FROM %some-server-image%
COPY --from=rtnews_frontend /app/public %location%
...something
```

**Comment by umputun** [comment]
- что такое " в папке public" ? это /app/public ? 
- "9000 экспозится для дев сервера." - Dockerfile oн для подашен, в нем никаких заготовок для dev быть не должно. Если надо 9000 экспозить то это должно быть сделано на уровен дев композа
- построение контейнера очень странное, они зачем-то друг от друга делают FROM. Это убивает весь смысл multistage build

> Что-то такое надо добавить в твой основной пайплайн

у меня  нет никакого "основного пайплайн", ожидается что контейнер принесет (после запуска dockerfile) все в какой-то каталог. Он так делал в /var/webapp раньше

**Comment by reeywhaar** [comment]
Да, это в /app/public.
Мы просто не обсуждали вообще вопрос билда, тут как-то резко все происходит.
То есть мне нужно сделать этот докер файл основным, убрать 9000, и класть билд в /var/webapp?
Серверу еще нужно сделать fallback на index.html

**Comment by umputun** [comment]
в /app/public пусто. 

```
dk run -it --rm umputun/rtnews-ui
/app # ls
node_modules       package-lock.json  package.json       public
/app # ls public/
/app # exit
```

> То есть мне нужно сделать этот докер файл основным, убрать 9000, и класть билд в /var/webapp?

да/ var/www/webapp, и VOLUME /var/www/webapp

> Серверу еще нужно сделать fallback на index.html

на nginx news есть root /var/www/webapp;

**Comment by umputun** [comment]
прочие проблемы:

- в контейнере ничего иного не надо, только public с файлами
- в контейнере в виде CMD (или entry point)  надо что-то типа вечного sleep. Запуск sh не будет работать
- строить контейнер можно в 2 этапа - build и второй, который FROM alpine и копирует public

**Comment by umputun** [comment]
переключил обратно, на пред. версии. Мы пока явно не готовы

**Comment by umputun** [comment]
для понятности:

nginx контейнер делает вот это:

```       
 volumes_from:
      - news-webapp:ro
```

**Comment by umputun** [comment]
#8 проблемы решило, задеплоил

**Comment by reeywhaar** [comment]
Количество комментариев фетчится с дискаса, это временно?

**Comment by umputun** [comment]
хмм, что-то я свое не смерджил. счас я его

**Comment by umputun** [comment]
починил, да

**Comment by reeywhaar** [comment]
https://news.radio-t.com/post/amazon-and-oracle-in-database-drama
Сейчас показывает 404, из-за того, что нету фоллбэка на index.html в nginx.

edit: хмм, фоллбэк есть, но видимо остался какой-то старый роут на /post/*

**Comment by umputun** [comment]
xмм,  там было (и осталось) нечто и до этого:

```
  location /post {
        rewrite ^/post/(.*)$ /post/index.html?slug=$1 break;
    }
```

**Comment by reeywhaar** [comment]
Это правило больше не нужно

**Comment by umputun** [comment]
удалил

**Comment by reeywhaar** [comment]
Заметил, что в https://news.radio-t.com/archive/ количество комментариев тоже видимо с дискаса

**Comment by umputun** [comment]
это маловероятно. Кода для дискаса больше просто нет в том, что сейчас бежит

**Comment by reeywhaar** [comment]
Возможно просто для архивных новостей не обновляется количество комментариев. Надо наверное убрать там ссылку. И наверное надо убрать сортировку "по дате новости". ?

**Comment by umputun** [comment]
> Возможно просто для архивных новостей не обновляется количество комментариев. Надо наверное убрать там ссылку.

скорее всего так всегда и было, да просто убрать. 

> И наверное надо убрать сортировку "по дате новости". ?

ok

**Comment by reeywhaar** [comment]
И еще заметил, что кешируется сам `index.html`: выглядит как будто что-то пошло не так и новости не загрузились. После cmd-R все проходит, но конфузит.

```
HTTP/1.1 304 Not Modified
Server: nginx
Date: Sun, 18 Nov 2018 04:10:04 GMT
Last-Modified: Sat, 17 Nov 2018 23:45:33 GMT
Connection: keep-alive
ETag: "5bf0a81d-92b"
Strict-Transport-Security: max-age=63072000; includeSubdomains; preload
```
